"""added constraints for Position

Revision ID: 1f4594436e2b
Revises: 88aa4a0edb7b
Create Date: 2022-01-27 16:04:47.693997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f4594436e2b'
down_revision = '88aa4a0edb7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'position', ['position_name'])
    op.drop_constraint('teacher_position_id_fkey', 'teacher', type_='foreignkey')
    op.create_foreign_key(None, 'teacher', 'position', ['position_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teacher', type_='foreignkey')
    op.create_foreign_key('teacher_position_id_fkey', 'teacher', 'position', ['position_id'], ['id'])
    op.drop_constraint(None, 'position', type_='unique')
    # ### end Alembic commands ###
