"""changed password type

Revision ID: 62ccb0a9bb03
Revises: d800626354e4
Create Date: 2022-02-02 18:37:47.326165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62ccb0a9bb03'
down_revision = 'd800626354e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
