"""renamed fields

Revision ID: 70de45373e17
Revises: 1c9ddeee3e8b
Create Date: 2022-01-31 14:55:35.829195

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '70de45373e17'
down_revision = '1c9ddeee3e8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('group', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('group', sa.Column('date', sa.Date(), nullable=False))
    op.drop_column('group', 'updated_on')
    op.drop_column('group', 'group_date')
    op.drop_column('group', 'created_on')
    op.add_column('position', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('position', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('position', 'updated_on')
    op.drop_column('position', 'created_on')
    op.add_column('specialty', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('specialty', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('specialty', sa.Column('date', sa.Date(), nullable=False))
    op.drop_column('specialty', 'updated_on')
    op.drop_column('specialty', 'specialty_date')
    op.drop_column('specialty', 'created_on')
    op.add_column('student', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('student', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('student', 'updated_on')
    op.drop_column('student', 'created_on')
    op.add_column('subject', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('subject', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('subject', 'updated_on')
    op.drop_column('subject', 'created_on')
    op.add_column('teacher', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('teacher', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('teacher', 'updated_on')
    op.drop_column('teacher', 'created_on')
    op.add_column('user', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('user', 'updated_on')
    op.drop_column('user', 'created_on')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('updated_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.add_column('teacher', sa.Column('created_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('teacher', sa.Column('updated_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('teacher', 'updated_at')
    op.drop_column('teacher', 'created_at')
    op.add_column('subject', sa.Column('created_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('subject', sa.Column('updated_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('subject', 'updated_at')
    op.drop_column('subject', 'created_at')
    op.add_column('student', sa.Column('created_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('student', sa.Column('updated_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('student', 'updated_at')
    op.drop_column('student', 'created_at')
    op.add_column('specialty', sa.Column('created_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('specialty', sa.Column('specialty_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('specialty', sa.Column('updated_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('specialty', 'date')
    op.drop_column('specialty', 'updated_at')
    op.drop_column('specialty', 'created_at')
    op.add_column('position', sa.Column('created_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('position', sa.Column('updated_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('position', 'updated_at')
    op.drop_column('position', 'created_at')
    op.add_column('group', sa.Column('created_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('group', sa.Column('group_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('group', sa.Column('updated_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('group', 'date')
    op.drop_column('group', 'updated_at')
    op.drop_column('group', 'created_at')
    # ### end Alembic commands ###
