"""changed type for year field

Revision ID: 74932c80411d
Revises: f7ef72f890ce
Create Date: 2022-01-31 19:18:40.059236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74932c80411d'
down_revision = 'f7ef72f890ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subject', 'year',
               existing_type=sa.DATE(),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subject', 'year',
               existing_type=sa.Integer(),
               type_=sa.DATE(),
               existing_nullable=False)
    # ### end Alembic commands ###
