"""empty message

Revision ID: 92245fd38e55
Revises: 9c4a474be997
Create Date: 2022-01-25 18:46:06.374421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92245fd38e55'
down_revision = '9c4a474be997'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###
