"""added BaseModel, with id, created_on, updated_on and methods

Revision ID: bdd07946f41f
Revises: c9995db96297
Create Date: 2022-01-28 18:15:17.703016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdd07946f41f'
down_revision = 'c9995db96297'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('position', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('position', sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('position', 'position_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=60),
               existing_nullable=False)
    op.add_column('student', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('student', sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('teacher', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('teacher', sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('user', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('user', sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_on')
    op.drop_column('user', 'created_on')
    op.drop_column('teacher', 'updated_on')
    op.drop_column('teacher', 'created_on')
    op.drop_column('student', 'updated_on')
    op.drop_column('student', 'created_on')
    op.alter_column('position', 'position_name',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('position', 'updated_on')
    op.drop_column('position', 'created_on')
    # ### end Alembic commands ###
