"""renamed column

Revision ID: c31a9f1fb6d6
Revises: 62dd0dc7d992
Create Date: 2022-01-28 19:33:26.275044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c31a9f1fb6d6'
down_revision = '62dd0dc7d992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specialty', sa.Column('specialty_date', sa.Date(), nullable=False))
    op.drop_column('specialty', 'specialty_year')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specialty', sa.Column('specialty_year', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('specialty', 'specialty_date')
    # ### end Alembic commands ###
