"""move is_active field to specific user

Revision ID: c9995db96297
Revises: 1f4594436e2b
Create Date: 2022-01-28 16:39:56.322621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9995db96297'
down_revision = '1f4594436e2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('teacher', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('teacher', 'is_active')
    op.drop_column('student', 'is_active')
    # ### end Alembic commands ###
