"""added TokenBlocklistModel

Revision ID: d2fa49c55fff
Revises: fb9bd006e887
Create Date: 2022-02-22 17:32:22.311481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2fa49c55fff'
down_revision = 'fb9bd006e887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blocklist_model',
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('jti')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token_blocklist_model')
    # ### end Alembic commands ###
