"""renamed date to year

Revision ID: e5055e352386
Revises: 70de45373e17
Create Date: 2022-01-31 16:32:08.762068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5055e352386'
down_revision = '70de45373e17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('year', sa.Integer(), nullable=False))
    op.drop_column('group', 'date')
    op.add_column('specialty', sa.Column('year', sa.Integer(), nullable=False))
    op.drop_column('specialty', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specialty', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('specialty', 'year')
    op.add_column('group', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('group', 'year')
    # ### end Alembic commands ###
