"""renamed subject_date to year

Revision ID: f7ef72f890ce
Revises: e5055e352386
Create Date: 2022-01-31 16:52:32.702103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7ef72f890ce'
down_revision = 'e5055e352386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject', sa.Column('year', sa.Date(), nullable=False))
    op.drop_column('subject', 'subject_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject', sa.Column('subject_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('subject', 'year')
    # ### end Alembic commands ###
