"""added assignment model

Revision ID: fb9bd006e887
Revises: 01da1dd63710
Create Date: 2022-02-18 11:34:38.882863

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fb9bd006e887'
down_revision = '01da1dd63710'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('assignment_name_key', 'assignment', type_='unique')
    op.drop_column('teacher', 'updated_at')
    op.drop_column('teacher', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('teacher', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.create_unique_constraint('assignment_name_key', 'assignment', ['name'])
    # ### end Alembic commands ###
